message(STATUS DOXYGEN=${DOXYGEN})
if(DOXYGEN)
  find_package(Doxygen
    REQUIRED dot
    OPTIONAL_COMPONENTS mscgen dia
  )

  if(Doxygen_FOUND)
    set(DOXYGEN_OUTPUT_DIRECTORY      ${CMAKE_BINARY_DIR}/docs)
    set(DOXYGEN_EXTRACT_ALL           YES)
    set(DOXYGEN_FULL_SIDEBAR          YES)
    set(DOXYGEN_MARKDOWN_SUPPORT      YES)
    set(DOXYGEN_USE_MATHJAX           YES)
    set(GOXYGEN_GENERATE_TREEVIEW     YES)
    set(DOXYGEN_SHOW_INCLUDE_FILES    YES)
    set(DOXYGEN_CLASS_DIAGRAMS        YES)
    set(DOXYGEN_EXTRACT_ALL           YES)
    set(DOXYGEN_CLASS_DIAGRAMS        YES)
    set(DOXYGEN_HIDE_UNDOC_RELATIONS  NO)
    set(DOXYGEN_HAVE_DOT              YES)
    set(DOXYGEN_CLASS_GRAPH           YES)
    set(DOXYGEN_CALL_GRAPH            YES)
    set(DOXYGEN_CALLER_GRAPH          YES)
    set(DOXYGEN_COLLABORATION_GRAPH   YES)
    set(DOXYGEN_BUILTIN_STL_SUPPORT   YES)
    set(DOXYGEN_EXTRACT_PRIVATE       YES)
    set(DOXYGEN_EXTRACT_PACKAGE       YES)
    set(DOXYGEN_EXTRACT_STATIC        YES)
    set(DOXYGEN_EXTRACT_LOCALMETHODS  YES)
    set(DOXYGEN_UML_LOOK              YES)
    set(DOXYGEN_UML_LIMIT_NUM_FIELDS  50)
    set(DOXYGEN_TEMPLATE_RELATIONS    YES)
    set(DOXYGEN_DOT_GRAPH_MAX_NODES   100)
    set(DOXYGEN_MAX_DOT_GRAPH_DEPTH   0)
    doxygen_add_docs(doxygen ${CMAKE_SOURCE_DIR}/src)
  else()
    message("Doxygen need to be installed for generating the doxygen documentation")
  endif()
endif()
